Repository db-ux-design-system/examples, pull requests merged in 2024-11, with the labels that each got.

#1524 fix: cicd
  .github/workflows/default.yml
  angular17-example/package-lock.json
  angular17-example/package.json
  angular17-example/src/app/app.component.html
  angular17-example/src/styles.scss
  e2e/Dockerfile
  e2e/__snapshots__/angular-example.spec.ts-snapshots/Angular-Example-should-match-screenshot-1-chromium-linux.png
  e2e/__snapshots__/angular-example.spec.ts-snapshots/Angular-Example-should-match-screenshot-1-firefox-linux.png
  e2e/__snapshots__/angular-example.spec.ts-snapshots/Angular-Example-should-match-screenshot-1-mobile-chrome-linux.png
  e2e/__snapshots__/angular-example.spec.ts-snapshots/Angular-Example-should-match-screenshot-1-mobile-safari-linux.png
  e2e/__snapshots__/angular-example.spec.ts-snapshots/Angular-Example-should-match-screenshot-1-webkit-linux.png
  e2e/__snapshots__/react-example.spec.ts-snapshots/React-Example-should-match-screenshot-1-chromium-linux.png
  e2e/__snapshots__/react-example.spec.ts-snapshots/React-Example-should-match-screenshot-1-firefox-linux.png
  e2e/__snapshots__/react-example.spec.ts-snapshots/React-Example-should-match-screenshot-1-mobile-chrome-linux.png
  e2e/__snapshots__/react-example.spec.ts-snapshots/React-Example-should-match-screenshot-1-mobile-safari-linux.png
  e2e/__snapshots__/react-example.spec.ts-snapshots/React-Example-should-match-screenshot-1-webkit-linux.png
  e2e/__snapshots__/vue-example.spec.ts-snapshots/Vue-Example-should-match-screenshot-1-chromium-linux.png
  e2e/__snapshots__/vue-example.spec.ts-snapshots/Vue-Example-should-match-screenshot-1-firefox-linux.png
  e2e/__snapshots__/vue-example.spec.ts-snapshots/Vue-Example-should-match-screenshot-1-mobile-chrome-linux.png
  e2e/__snapshots__/vue-example.spec.ts-snapshots/Vue-Example-should-match-screenshot-1-mobile-safari-linux.png
  e2e/__snapshots__/vue-example.spec.ts-snapshots/Vue-Example-should-match-screenshot-1-webkit-linux.png
  e2e/package-lock.json
  e2e/package.json
  react-example/src/App.tsx
  vue-example/README.md
  vue-example/src/App.vue
Labels: cicd, react, vue

#1523 fix: folder name
  .github/dependabot.yml
Labels: bug, cicd

#1553 refactor: updated auto-merge capability
  .github/workflows/99-auto-merge.yml
Labels: cicd
